### ISSUE TITLE
Check behavior of HKEY_CURRENT_USER\Software\Classes

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfwinreg#121]
Per https://github.com/log2timeline/dfwinreg/pull/120 check behavior of HKEY_CURRENT_USER\Software\Classes when UsrClass.dat is defined.

**Comment by Onager** [comment]
Please add a test for [GetRootKey ](https://github.com/log2timeline/dfwinreg/blob/968d9c48441a671287b4f29f3051084e62dfd960/dfwinreg/registry.py#L447) as part of this check.
