### ISSUE TITLE
Missing separator character in certain registry paths

### ISSUE THREAD

**Issue by ict** [log2timeline/dfwinreg#180]
Hello,

I noticed a problem when querying a particular registry path that will be resolved using the VIRTUAL_KEYS mechanism.
A basic example:

```python
reg_key = registry.GetKeyByPath('HKEY_USERS\\S-1-5-21-XXXXX-1000\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\UserAssist\\{CEBFF5CD-ACE2-4F4F-9178-9926F41749EA}\\Count')
print(reg_key.path)
```
Given a working environment, this will output
```
'HKEY_USERS\S-1-5-21-XXXXX-1000Software\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\{CEBFF5CD-ACE2-4F4F-9178-9926F41749EA}\Count'
```
Notice the missing `\` between the SID and `Software`.

While debugging, I traced this to the splitting and concatenating of the registry path, the culprit seems to be this line:
https://github.com/log2timeline/dfwinreg/blob/3cae45c90501b2f5663a041bf29edbbb3bb5c73b/dfwinreg/registry.py#L412

Can you confirm this is an error within `dfwinreg` or am I doing something wrong?

**Comment by joachimmetz** [comment]
@ict thx for the report based on your description this sounds like an issue in the path handling code, I'll have a closer look when time permits

**Comment by joachimmetz** [comment]
Changes and test coverage in https://github.com/log2timeline/dfwinreg/pull/188
