### ISSUE TITLE
setup.cfg uses deprecated parameter license_file

### ISSUE THREAD

**Issue by vwegert** [log2timeline/dfwinreg#201]
When compiling the dfwinreg-20211207 package, I get a SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.

If I read https://setuptools.pypa.io/en/latest/userguide/declarative_config.html correctly, the singular form is an alias for the plural form: "The aliases given below are supported for compatibility reasons, but their use is not advised."

I'm aware that this is an extremely LOW priority issue that can be fixed whenever convenient.

**Comment by joachimmetz** [comment]
Has already been addressed in HEAD https://github.com/log2timeline/dfwinreg/blob/main/setup.cfg#L2
