### ISSUE TITLE
create documentation

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfwinreg#30]
- [x] how to use

**Comment by Sim4n6** [comment]
Could you please provide more details, I would like to start here... 

 - Is this the repository to make pull request to in order to enhance the documentation/wiki ? https://github.com/log2timeline/dfwinreg.wiki.git

**Comment by joachimmetz** [comment]
So https://github.com/log2timeline/dfwinreg.wiki.git is the github wiki git repo, however that does not neatly intergrates into the github review workflow. For plaso we have therefore switched to readthedocs in a docs subdirectory, which is likely the better way to go here as well.

@Onager any additional comments? preferences?

**Comment by joachimmetz** [comment]
Changes to move documentation to readthedocs https://github.com/log2timeline/dfwinreg/pull/151

**Comment by joachimmetz** [comment]
Basic documentation on code snippets is here https://dfwinreg.readthedocs.io/en/latest/sources/Code-snippets.html
