### ISSUE TITLE
dfvfs implementation

### ISSUE THREAD

**Issue by bobbypistol** [log2timeline/dfwinreg#36]
Hi

I'm wondering what the easiest implementation would be with dfvfs, as can you use a NewPathSpec as source? The snippet doesn't seems to be the best solution with dfvfs as backend.

Oh btw, impressed with all your libraries

**Comment by joachimmetz** [comment]
I'm missing context in your question, so I'm not sure what you are asking of telling me. Can you please describe to me:

* what you want to accomplish
* what snippet you are looking at, maybe add a link?

**Comment by bobbypistol** [comment]
I was referring to the [code snippet](https://github.com/log2timeline/dfwinreg/wiki/Code-snippets). The example uses a file on disk I assume. We are using DfVFS as backend to access all our images, I would like for example to open the registry from a [file like object](https://github.com/log2timeline/dfvfs/blob/b168f0edd6dc8624583c1248593e26de0c7a703a/dfvfs/resolver/context.py#L87). The question is more what is the DfVFS recommended way to implement dfwinreg to acces the registry. I guess this is also implemented in Plaso? Sorry for the short explanation.

**Comment by joachimmetz** [comment]
> Sorry for the short explanation.

No worries, it is just hard to give a decent answer without the necessary context.

So the snippet describes a single Registry file. I think what you want has been implemented in the winreg-kb scripts. Have a look at https://github.com/libyal/winreg-kb and in particular https://github.com/libyal/winreg-kb/blob/master/winreg_kb/collector.py

**Comment by joachimmetz** [comment]
I assumed this answered your question, closing issue. Feel to reopen if needed.
