### ISSUE TITLE
Tests fail with Python3

### ISSUE THREAD

**Issue by hillu** [log2timeline/dfwinreg#43]
Running `python3 run_tests.py` throws the following error:

```
======================================================================
ERROR: testGetDataAsObject (fake.FakeWinRegistryValueTest)
Tests the GetDataAsObject function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bengen/p/deb/plaso/dfwinreg/tests/fake.py", line 334, in testGetDataAsObject
    registry_value.GetDataAsObject()
  File "./dfwinreg/fake.py", line 359, in GetDataAsObject
    return self._data.decode(u'utf-16-le')
AttributeError: 'str' object has no attribute 'decode'

----------------------------------------------------------------------
```

Line 329ff. of tests/fake.py seems to be the first spot where a string instead of a bytes is passed as `data` to `fake.FakeWinRegistryValue()`.

This was found while trying to build dfwinreg/20170301-1 for Debian.

**Comment by joachimmetz** [comment]
Travis disagrees https://travis-ci.org/log2timeline/dfwinreg/jobs/206890569 but I'll have a look.

So https://github.com/log2timeline/dfwinreg/blob/master/tests/fake.py#L334 is expecting WinRegistryValueError and https://github.com/log2timeline/dfwinreg/blob/master/dfwinreg/fake.py#L359 catches UnicodeError but AttributeError is raised instead.

I'll change https://github.com/log2timeline/dfwinreg/blob/master/dfwinreg/fake.py#L359 to catch AttributeError or check for the presence of decode.

Can you indicate which version of python 3 you are testing with?

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/320330043

**Comment by hillu** [comment]
* Joachim Metz:

> Can you indicate which version of python 3 you are testing with?

$ python3 --version
Python 3.5.3

**Comment by joachimmetz** [comment]
Code updated please try again. Closing issue feel free to reopen if issue persists.

**Comment by hillu** [comment]
Sorry. :-)

After cherry-picking ef732b15cc289261ca6722c6b0017fb75ea376b4 I get the same type of error at a different code location.

```
======================================================================
ERROR: testGetDataAsObject (fake.FakeWinRegistryValueTest)
Tests the GetDataAsObject function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./dfwinreg/fake.py", line 359, in GetDataAsObject
    return self._data.decode(u'utf-16-le')
AttributeError: 'str' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bengen/p/deb/plaso/dfwinreg/tests/fake.py", line 334, in testGetDataAsObject
    registry_value.GetDataAsObject()
  File "./dfwinreg/fake.py", line 365, in GetDataAsObject
    u'{2:s}').format(type(self._data), self._name, exception))
TypeError: unsupported format string passed to type.__format__
```

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/321770043/

**Comment by hillu** [comment]
* Joachim Metz:

> https://codereview.appspot.com/321770043/

With that patch applied, the build and test no longer fails.

Cheers,
-Hilko

**Comment by joachimmetz** [comment]
Closing for realz now ;)
